In [1]:
import pandas as pd
import numpy as np
import xlrd
from pathlib import Path
import glob
import os

In [3]:
#set to the file extension of "to-be-merged" files
ext = ".txt"
#set to your working directory
dir_path = 'C:\\Census Data\\data'
#set to the name of your output file
#results = 'ACSSF_2012_2016_Full.txt'


    
files = os.listdir('C:\\Census Data\\data')

#e20161ak0001000
#e = estimates
#2016 = year
#1 = 1 year estimate vs. 5 year
#ak = state
#0001 = sequence number
#000 = iterationID


files2 = [k for k in files if 'e' in k]
#files3 = [k for k in files2 if 'e2016' in k]
files3 = [k for k in files2 if '0041' in k]


string = 'C:\\Census Data\\data\\'

files4 = [string + x for x in files3]

files4

['C:\\Census Data\\data\\e20171ak0041000.txt',
 'C:\\Census Data\\data\\e20171al0041000.txt',
 'C:\\Census Data\\data\\e20171ar0041000.txt',
 'C:\\Census Data\\data\\e20171az0041000.txt',
 'C:\\Census Data\\data\\e20171ca0041000.txt',
 'C:\\Census Data\\data\\e20171co0041000.txt',
 'C:\\Census Data\\data\\e20171ct0041000.txt',
 'C:\\Census Data\\data\\e20171dc0041000.txt',
 'C:\\Census Data\\data\\e20171de0041000.txt',
 'C:\\Census Data\\data\\e20171fl0041000.txt',
 'C:\\Census Data\\data\\e20171ga0041000.txt',
 'C:\\Census Data\\data\\e20171hi0041000.txt',
 'C:\\Census Data\\data\\e20171ia0041000.txt',
 'C:\\Census Data\\data\\e20171id0041000.txt',
 'C:\\Census Data\\data\\e20171il0041000.txt',
 'C:\\Census Data\\data\\e20171in0041000.txt',
 'C:\\Census Data\\data\\e20171ks0041000.txt',
 'C:\\Census Data\\data\\e20171ky0041000.txt',
 'C:\\Census Data\\data\\e20171la0041000.txt',
 'C:\\Census Data\\data\\e20171ma0041000.txt',
 'C:\\Census Data\\data\\e20171md0041000.txt',
 'C:\\Census Data\\data\\e20171me0041000.txt',
 'C:\\Census Data\\data\\e20171mi0041000.txt',
 'C:\\Census Data\\data\\e20171mn0041000.txt',
 'C:\\Census Data\\data\\e20171mo0041000.txt',
 'C:\\Census Data\\data\\e20171ms0041000.txt',
 'C:\\Census Data\\data\\e20171mt0041000.txt',
 'C:\\Census Data\\data\\e20171nc0041000.txt',
 'C:\\Census Data\\data\\e20171nd0041000.txt',
 'C:\\Census Data\\data\\e20171ne0041000.txt',
 'C:\\Census Data\\data\\e20171nh0041000.txt',
 'C:\\Census Data\\data\\e20171nj0041000.txt',
 'C:\\Census Data\\data\\e20171nm0041000.txt',
 'C:\\Census Data\\data\\e20171nv0041000.txt',
 'C:\\Census Data\\data\\e20171ny0041000.txt',
 'C:\\Census Data\\data\\e20171oh0041000.txt',
 'C:\\Census Data\\data\\e20171ok0041000.txt',
 'C:\\Census Data\\data\\e20171or0041000.txt',
 'C:\\Census Data\\data\\e20171pa0041000.txt',
 'C:\\Census Data\\data\\e20171pr0041000.txt',
 'C:\\Census Data\\data\\e20171ri0041000.txt',
 'C:\\Census Data\\data\\e20171sc0041000.txt',
 'C:\\Census Data\\data\\e20171sd0041000.txt',
 'C:\\Census Data\\data\\e20171tn0041000.txt',
 'C:\\Census Data\\data\\e20171tx0041000.txt',
 'C:\\Census Data\\data\\e20171us0041000.txt',
 'C:\\Census Data\\data\\e20171ut0041000.txt',
 'C:\\Census Data\\data\\e20171va0041000.txt',
 'C:\\Census Data\\data\\e20171vt0041000.txt',
 'C:\\Census Data\\data\\e20171wa0041000.txt',
 'C:\\Census Data\\data\\e20171wi0041000.txt',
 'C:\\Census Data\\data\\e20171wv0041000.txt',
 'C:\\Census Data\\data\\e20171wy0041000.txt',
 'C:\\Census Data\\data\\m20171de0041000.txt',
 'C:\\Census Data\\data\\m20171me0041000.txt',
 'C:\\Census Data\\data\\m20171ne0041000.txt']

In [21]:


my_cols = ["1","YEAR","STATE","4","SEQ","LOGRECNO","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25",
"26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48",
"49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72",
"73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96",
"97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116",
"117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136",
"137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156",
"157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176",
"177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196",
"197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214",
"215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234",
"235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253",
"254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272",
"273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291",
"292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311",
"312","313","314","315","316","317","318","319","320","321","322","323","324","325","326","327","328","329","330",
"331","332","333","334","335","336","337","338","339","340","341","342","343","344","345","346","347","348","349","350",
"351","352","353","354","355","356","357","358","359","360","361","362","363","364","365","366","367","368","369","370",
"371","372","373","374","375","376","377","378","379","380","381","382","383","384","385","386","387","388","389","390",
"391","392","393","394","395","396","397","398","399","400","401","402","403","404","405","406","407","408","409",
"410","411","412","413","414","415","416","417","418","419","420","421","422","423","424","425","426","427","428","429",
"430","431","432","433","434","435","436","437","438","439","440","441","442","443","444","445","446","447","448",
"449","450","451","452","453","454","455","456","457","458","459","460","461","462","463","464","465","466","467",
"468","469","470","471","472","473","474","475","476","477","478","479","480","481","482","483","484","485","486",
"487","488","489","490","491","492","493","494","495","496","497","498","499","500","501","502","503","504","505",
"506","507","508","509","510","511","512","513","514","515","516","517","518","519","520","521","522","523","524",
"525","526","527","528","529","530","531","532","533","534","535","536","537","538","539","540","541","542","543",
"544","545","546","547","548","549","550","551","552","553","554","555","556","557"]

fullfile = pd.read_csv('C:\\Census Data\\data\\e20175ma0043000.txt', names=my_cols, engine='python')

fullfile = fullfile.loc[fullfile['557'] == 0]


fullfile

Empty DataFrame
Columns: [1, YEAR, STATE, 4, SEQ, LOGRECNO, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]
Index: []

[0 rows x 557 columns]

In [22]:
for f in files4:
  if f.endswith(ext):
    data = open(f)
    
    out = pd.read_csv(data, names=my_cols, engine='python')
    #out = open(results, 'a')
    
    
    #out2 = out.loc[out['5'] == 41]
    out2 = out
    fullfile = pd.concat([fullfile, out2], ignore_index=True)
                         
    #fullfile.merge(out, how='outer')
    #fullfile = [fullfile, out]
    
    
    #for l in data:
      #print(l, file=out)
    data.close()
    #out.close()
#fullfile.to_csv("csvfile.csv", sep=',', encoding='utf-8')

In [23]:
fullfile.head()

,1,YEAR,STATE,4,SEQ,LOGRECNO,7,8,9,10,...,548,549,550,551,552,553,554,555,556,557
0,ACSSF,20170,ak,0,41,1,357793.0,16310.0,25218.0,13745.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACSSF,20170,ak,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACSSF,20170,ak,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACSSF,20170,ak,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACSSF,20170,ak,0,41,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
fullfile.to_csv("csvfile.csv", sep=',', encoding='utf-8')

In [25]:
#Create Reference Log Table
fullfile["STATE"] = fullfile['STATE'].str.upper() #uppercase space

In [26]:
fullfile = fullfile.dropna(axis=1, how='all') #, thresh=None, subset=None, inplace=False)
fullfile.head()

,1,YEAR,STATE,4,SEQ,LOGRECNO,7,8,9,10,...,228,229,230,231,232,233,234,235,236,237
0,ACSSF,20170,AK,0,41,1,357793.0,16310.0,25218.0,13745.0,...,383.0,1143.0,1039.0,862.0,3038.0,3271.0,1437.0,1616.0,167.0,13.0
1,ACSSF,20170,AK,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACSSF,20170,AK,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACSSF,20170,AK,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACSSF,20170,AK,0,41,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
fullfile2 = fullfile

columnnames = pd.read_excel(r"C:\Census Data\References\2017_5yr_Summary_FileTemplates\xls_temp\Seq41.xlsx", sheet_name='e')
values = {'FILEID': "1", 'FILETYPE': "YEAR", 'STUSAB': "STATE", 
                                'CHARITER': "4","SEQUENCE" : "SEQ", "LOGRECNO": "LOGRECNO"
          }

columnnames2 = columnnames.fillna(value = values)

name_str = columnnames2.transpose() 


fullfile2.columns = name_str.values

fullfile2.columns = fullfile2.columns.map(str)

fullfile2.columns = fullfile2.columns.str.strip().str.replace(":", '').str.replace("'", '').str.replace(',', '').str.replace('(', '').str.replace(')', '')

#fullfile2

In [29]:
#fullfile2.to_csv("csvfile.csv", sep=',', encoding='utf-8')

In [45]:
sheet_names = ['ak',	'al',	'ar',	'az',	'ca',	'co',	'ct',	'dc',	'de',
'fl',	'ga',	'hi',	'ia',	'id',	'il',	'in',	'ks',	'ky',
'la',	'ma',	'md',	'me',	'mi',	'mn',	'mo',	'ms',	'mt',
'nc',	'nd',	'ne',	'nh',	'nj',	'nm',	'nv',	'ny',	'oh',
'ok',	'or',	'pa',	'pr',	'ri',	'sc',	'sd',	'tn',	'tx',
'us',	'ut',	'va',	'vt',	'wa',	'wi',	'wv',	'wy'	
]
dfs = pd.read_excel(r"C:\Census Data\References\5_year_Mini_Geo.xlsx", sheet_name=sheet_names)
LogRecRef = pd.concat((df.assign(source=sheet) for sheet, df in dfs.items()), ignore_index=True)

In [46]:
fullfile.rename(columns = {"STUSAB":"STATE"}, inplace = True)
fullfile.head(10)

,FILEID,FILETYPE,STATE,CHARITER,SEQUENCE,LOGRECNO,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY% Workers 16 years and over%Total,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Agriculture forestry fishing and hunting and mining,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Construction,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Manufacturing,...,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Wholesale trade,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Retail trade,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Transportation and warehousing and utilities,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Information and finance and insurance and real estate and rental and leasing,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Professional scientific and management and administrative and waste management services,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Educational services and health care and social assistance,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Arts entertainment and recreation and accommodation and food services,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Other services except public administration,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Public administration,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Armed forces
0,ACSSF,20170,AK,0,41,1,357793.0,16310.0,25218.0,13745.0,...,383.0,1143.0,1039.0,862.0,3038.0,3271.0,1437.0,1616.0,167.0,13.0
1,ACSSF,20170,AK,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACSSF,20170,AK,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACSSF,20170,AK,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACSSF,20170,AK,0,41,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ACSSF,20170,AK,0,41,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ACSSF,20170,AK,0,41,7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ACSSF,20170,AK,0,41,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ACSSF,20170,AK,0,41,9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ACSSF,20170,AK,0,41,10,162034.0,3753.0,9698.0,3587.0,...,232.0,208.0,134.0,237.0,1799.0,1513.0,321.0,608.0,15.0,0.0

In [47]:
#fullfile = fullfile['3'].str.upper() #uppercase space

LogRecRef.rename(columns = {"Logical Record Number":"LOGRECNO", "State":"STATE"}, inplace = True)

fullfile.head(10)
LogRecRef.head(1)

  STATE  LOGRECNO Geography ID Geography Name source
0    AK         1    04000US02         Alaska     ak

In [48]:
geofile = pd.merge(fullfile2, LogRecRef, on = ['LOGRECNO', 'STATE'], how = "inner")

In [49]:
#drop duplicate columns
geofile = geofile.drop(['source'], 1)

In [50]:
geofile

,FILEID,FILETYPE,STATE,CHARITER,SEQUENCE,LOGRECNO,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY% Workers 16 years and over%Total,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Agriculture forestry fishing and hunting and mining,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Construction,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Manufacturing,...,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Transportation and warehousing and utilities,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Information and finance and insurance and real estate and rental and leasing,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Professional scientific and management and administrative and waste management services,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Educational services and health care and social assistance,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Arts entertainment and recreation and accommodation and food services,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Other services except public administration,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Public administration,MEANS OF TRANSPORTATION TO WORK BY INDUSTRY FOR WORKPLACE GEOGRAPHY%Workers 16 years and over%Total%Worked at home%Armed forces,Geography ID,Geography Name
0,ACSSF,20170,AK,0,41,1,357793.0,16310.0,25218.0,13745.0,...,1039.0,862.0,3038.0,3271.0,1437.0,1616.0,167.0,13.0,04000US02,Alaska
1,ACSSF,20170,AK,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04001US02,Alaska -- Urban
2,ACSSF,20170,AK,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04043US02,Alaska -- Rural
3,ACSSF,20170,AK,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040A0US02,Alaska -- In metropolitan or micropolitan stat...
4,ACSSF,20170,AK,0,41,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C0US02,Alaska -- In metropolitan statistical area
5,ACSSF,20170,AK,0,41,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C1US02,Alaska -- In metropolitan statistical area -- ...
6,ACSSF,20170,AK,0,41,7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C2US02,Alaska -- In metropolitan statistical area -- ...
7,ACSSF,20170,AK,0,41,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040E0US02,Alaska -- In micropolitan statistical area
8,ACSSF,20170,AK,0,41,9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040E1US02,Alaska -- In micropolitan statistical area -- ...
9,ACSSF,20170,AK,0,41,10,162034.0,3753.0,9698.0,3587.0,...,134.0,237.0,1799.0,1513.0,321.0,608.0,15.0,0.0,040E2US02,Alaska -- In micropolitan statistical area -- ...
10,ACSSF,20170,AK,0,41,11,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040G0US02,Alaska -- Not in metropolitan or micropolitan ...
11,ACSSF,20170,AK,0,41,12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040H0US02,Alaska -- Not in metropolitan statistical area
12,ACSSF,20170,AK,0,41,13,162034.0,3753.0,9698.0,3587.0,...,134.0,237.0,1799.0,1513.0,321.0,608.0,15.0,0.0,05000US02013,"Aleutians East Borough, Alaska"
13,ACSSF,20170,AK,0,41,14,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02016,"Aleutians West Census Area, Alaska"
14,ACSSF,20170,AK,0,41,15,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02020,"Anchorage Municipality, Alaska"
15,ACSSF,20170,AK,0,41,16,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02050,"Bethel Census Area, Alaska"
16,ACSSF,20170,AK,0,41,17,162034.0,3753.0,9698.0,3587.0,...,134.0,237.0,1799.0,1513.0,321.0,608.0,15.0,0.0,05000US02060,"Bristol Bay Borough, Alaska"
17,ACSSF,20170,AK,0,41,18,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02068,"Denali Borough, Alaska"
18,ACSSF,20170,AK,0,41,19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02070,"Dillingham Census Area, Alaska"
19,ACSSF,20170,AK,0,41,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02090,"Fairbanks North Star Borough, Alaska"
20,ACSSF,20170,AK,0,41,21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02100,"Haines Borough, Alaska"
21,ACSSF,20170,AK,0,41,22,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02105,"Hoonah-Angoon Census Area, Alaska"
22,ACSSF,20170,AK,0,41,23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02110,"Juneau City and Borough, Alaska"
23,ACSSF,20170,AK,0,41,24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02122,"Kenai Peninsula Borough, Alaska"
24,ACSSF,20170,AK,0,41,25,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02130,"Ketchikan Gateway Borough, Alaska"
25,ACSSF,20170,AK,0,41,26,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US02150,"Kodiak Island Borough, Alaska"
26,ACSSF,20170,AL,0,41,1,1998361.0,27307.0,134340.0,278722.0,...,3332.0,9355.0,16680.0,9616.0,3877.0,4440.0,1159.0,0.0,04000US01,Alabama
27,ACSSF,20170,AL,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04001US01,Alabama -- Urban
28,ACSSF,20170,AL,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04043US01,Alabama -- Rural
29,ACSSF,20170,AL,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040A0US01,Alabama -- In metropolitan or micropolitan sta...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7984,ACSSF,20170,WV,0,41,33,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54041,"Lewis County, West Virginia"
7985,ACSSF,20170,WV,0,41,34,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54043,"Lincoln County, West Virginia"
7986,ACSSF,20170,WV,0,41,35,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54045,"Logan County, West Virginia"
7987,ACSSF,20170,WV,0,41,36,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54047,"McDowell County, West Virginia"
7988,ACSSF,20170,WV,0,41,37,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54049,"Marion County, West Virginia"
7989,ACSSF,20170,WV,0,41,38,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54051,"Marshall County, West Virginia"
7990,ACSSF,20170,WV,0,41,39,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54053,"Mason County, West Virginia"
7991,ACSSF,20170,WV,0,41,40,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54055,"Mercer County, West Virginia"
7992,ACSSF,20170,WV,0,41,41,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US54057,"Mineral County, West Virginia"
7993,ACSSF,20170,WY,0,41,1,286661.0,29006.0,22631.0,11056.0,...,660.0,816.0,3545.0,2642.0,919.0,1023.0,168.0,79.0,04000US56,Wyoming
7994,ACSSF,20170,WY,0,41,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04001US56,Wyoming -- Urban
7995,ACSSF,20170,WY,0,41,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04043US56,Wyoming -- Rural
7996,ACSSF,20170,WY,0,41,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040A0US56,Wyoming -- In metropolitan or micropolitan sta...
7997,ACSSF,20170,WY,0,41,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C0US56,Wyoming -- In metropolitan statistical area
7998,ACSSF,20170,WY,0,41,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C1US56,Wyoming -- In metropolitan statistical area --...
7999,ACSSF,20170,WY,0,41,7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040C2US56,Wyoming -- In metropolitan statistical area --...
8000,ACSSF,20170,WY,0,41,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040E0US56,Wyoming -- In micropolitan statistical area
8001,ACSSF,20170,WY,0,41,9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040E1US56,Wyoming -- In micropolitan statistical area --...
8002,ACSSF,20170,WY,0,41,10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040E2US56,Wyoming -- In micropolitan statistical area --...
8003,ACSSF,20170,WY,0,41,11,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040G0US56,Wyoming -- Not in metropolitan or micropolitan...
8004,ACSSF,20170,WY,0,41,12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,040H0US56,Wyoming -- Not in metropolitan statistical area
8005,ACSSF,20170,WY,0,41,13,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56001,"Albany County, Wyoming"
8006,ACSSF,20170,WY,0,41,14,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56003,"Big Horn County, Wyoming"
8007,ACSSF,20170,WY,0,41,15,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56005,"Campbell County, Wyoming"
8008,ACSSF,20170,WY,0,41,16,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56007,"Carbon County, Wyoming"
8009,ACSSF,20170,WY,0,41,17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56009,"Converse County, Wyoming"
8010,ACSSF,20170,WY,0,41,18,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56011,"Crook County, Wyoming"
8011,ACSSF,20170,WY,0,41,19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56013,"Fremont County, Wyoming"
8012,ACSSF,20170,WY,0,41,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56015,"Goshen County, Wyoming"
8013,ACSSF,20170,WY,0,41,21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05000US56017,"Hot Springs County, Wyoming"