In [1]:
import pandas as pd
import numpy as np
import xlrd
from pathlib import Path
import glob
import os

In [2]:
fullfile = pd.read_csv("C:\\Census Data - Uncleaned Headers\\Fullfile.csv", engine='python')

In [22]:
cols =[x for x in fullfile.columns[fullfile.columns.str.contains('STATE|LOGRECNO|GEOID|ATTAINMENT|ENROLLMENT|INCOME|ALLOCATION OF LANGUAGE SPOKEN AT HOME FOR THE POPULATION 5 YEARS|POPULATION UNDER 18 YEARS BY AGE|POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population')]]


fullfile2 = fullfile[cols]

fullfile2.columns = fullfile2.columns.str.strip().str.replace("%", '').str.replace('"', '')

cols2 =[x for x in fullfile2.columns[fullfile2.columns.str.contains('STATE|LOGRECNO|GEOID|SCHOOL ENROLLMENT BY DETAILED  LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school|    SCHOOL ENROLLMENT BY DETAILED  LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Total|SCHOOL ENROLLMENT BY DETAILED LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER BLACK OR AFRICAN AMERICAN ALONE for Black Or African American Alone Population 3 Years And Over Enrolled in school|SCHOOL ENROLLMENT BY DETAILED LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER HISPANIC OR LATINO for Hispanic Or Latino Population 3 Years And Over Enrolled in school|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households|    SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 12 to 14 years|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 15 to 17 years|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 3 and 4 years|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 5 years|   SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 6 to 8 years|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 9 to 11 years|SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households Under 3 years|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in college undergraduate years|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in grade 1 to grade 4|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in grade 5 to grade 8|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in grade 9 to grade 12|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in kindergarten|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Enrolled in nursery school preschool|SEQ41_SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Enrolled in school Graduate or professional school|SEQ41_SEX BY SCHOOL ENROLLMENT BY EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 16 TO 19 YEARS for Population 16 To 19 Years Female Not enrolled in school Not high school graduate|SEQ41_SEX BY SCHOOL ENROLLMENT BY EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 16 TO 19 YEARS for Population 16 To 19 Years Male Not enrolled in school Not high school graduate|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years 9th to 12th grade no diploma|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years Associates degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years Bachelors degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years Graduate or professional degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years High school graduate includes equivalency|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years Less than 9th grade|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Female 18 to 24 years Some college no degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years 9th to 12th grade no diploma|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years 9th to 12th grade no diploma|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Associates degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Associates degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Bachelors degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Graduate or professional degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years High school graduate includes equivalency|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years High school graduate includes equivalency|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Less than 9th grade|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Some college no degree|SEQ43_SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE POPULATION 18 YEARS AND OVER for Population 18 Years And Over Male 18 to 24 years Some college no degree|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Female 12 to 14 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Female 15 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Female 16 and 17 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Female 18 to 24 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Male 12 to 14 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Male 15 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Male 16 and 17 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Income in the past 12 months below poverty level Male 18 to 24 years|SEQ48_POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population For Whom Poverty Status Is Determined Total|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $10000 to $14999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $100000 to $124999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $125000 to $149999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $15000 to $19999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $150000 to $199999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $20000 to $24999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $200000 or more|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $25000 to $29999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $30000 to $34999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $35000 to $39999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $40000 to $44999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $45000 to $49999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $50000 to $59999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $60000 to $74999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families $75000 to $99999|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families Less than $10000|SEQ63_FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Families Total|SEQ64_MEDIAN FAMILY INCOME|SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Employed|SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Unemployed|SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Employed|SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Unemployed|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Female 10 to 14 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Female 15 to 19 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Female 20 to 24 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Female 25 to 29 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Female 5 to 9 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Male 10 to 14 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Male 15 to 19 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Male 20 to 24 years|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Male 25 to 29 year|SEX BY AGE FOR THE FOREIGN-BORN POPULATION for Foreign-Born Population Male 5 to 9 years')]]
FilteredFile = fullfile2[cols2]

#keep education
#keep Enrollment
#keep proverty
#keep income
#keep ALLOCATION OF LANGUAGE SPOKEN AT HOME FOR THE POPULATION 5 YEARS
#POPULATION UNDER 18 YEARS BY AGE

In [27]:
FilteredFile.head()
#168 
#FilteredFile.to_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FilteredFile.csv", sep=',', encoding='utf-8')

,STATE,LOGRECNO,GEOID,NATIVITY IN THE UNITED STATES for Total Population In The United States Total,NATIVITY IN THE UNITED STATES for Total Population In The United States Native,NATIVITY IN THE UNITED STATES for Total Population In The United States Foreign-Born,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households Under 3 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 3 and 4 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 5 years,...,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- Total,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- With own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- No own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- Total,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- With own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- No own children of the householder under 18 years,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Employed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Unemployed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Employed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Unemployed
0,MA,1,04000US25,6742143.0,5680682.0,1061461.0,1384240.0,210811.0,152154.0,74087.0,...,57815,48540,65264,40004,29020,55608,155152.0,20969.0,596395.0,55150.0
1,MA,2,04001US25,6204458.0,5170026.0,1034432.0,1272221.0,198339.0,142001.0,68810.0,...,57447,47248,65163,39155,28384,54984,148924.0,19942.0,543175.0,51799.0
2,MA,3,04043US25,537685.0,510656.0,27029.0,112019.0,12472.0,10153.0,5277.0,...,61691,57172,66930,57125,47369,65298,6228.0,1027.0,53220.0,3351.0
3,MA,4,040A0US25,6731449.0,5671874.0,1059575.0,1382109.0,210514.0,151903.0,74003.0,...,57722,48481,65155,40000,29021,55614,154859.0,20969.0,594991.0,55039.0
4,MA,5,040C0US25,6643396.0,5589108.0,1054288.0,1366073.0,208063.0,150446.0,73301.0,...,57953,48476,65453,40034,28978,55682,153551.0,20699.0,586181.0,54153.0

In [28]:
#College Enrollment

FilteredFileOrg = FilteredFile
#FilteredFileOrg = pd.read_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FilteredFile.csv", sep=',', encoding='utf-8')

#fullfile = pd.read_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FullFile.csv", engine='python')

cols =[x for x in fullfile.columns[fullfile.columns.str.contains('STATE|LOGRECNO|GEOID|ATTAINMENT|ENROLLMENT|INCOME|ALLOCATION OF LANGUAGE SPOKEN AT HOME FOR THE POPULATION 5 YEARS|POPULATION UNDER 18 YEARS BY AGE|POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population')]]

fullfile2 = fullfile[cols]

fullfile2.columns = fullfile2.columns.str.strip().str.replace("%", '').str.replace('"', '')

cols2 =[x for x in fullfile2.columns[fullfile2.columns.str.contains('GEOID|college or graduate school|18 and 19 years')]]
FilteredFileAdd = fullfile2[cols2]



#--File41

#SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over% Male% Enrolled in public college or graduate school% 18 to 24 years
#SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over% Male% Enrolled in private college or graduate school% 18 to 24 years
#SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over% Female% Enrolled in public college or graduate school% 18 to 24 years
#SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over% Female% Enrolled in private college or graduate school% 18 to 24 years
#SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over% Male% Enrolled in public school% 18 and 19 years
#SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over% Male% Enrolled in private school% 18 and 19 years

In [29]:
FilteredFileAdd.head()

,GEOID,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Male Enrolled in public school 18 and 19 years,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Male Enrolled in private school 18 and 19 years,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Male Not enrolled in school 18 and 19 years,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Female Enrolled in public school 18 and 19 years,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Female Enrolled in private school 18 and 19 years,SEQ41_SEX BY SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER for Population 3 Years And Over Female Not enrolled in school 18 and 19 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Male Enrolled in public college or graduate school,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Male Enrolled in public college or graduate school 15 to 17 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Male Enrolled in public college or graduate school 18 to 24 years,...,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 15 to 17 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 18 to 24 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 25 to 34 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 35 years and over,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 15 to 17 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 18 to 24 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 25 to 34 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 35 years and over
0,04000US25,52784.0,32743.0,18026.0,51829.0,41413.0,12772.0,130722.0,585.0,84213.0,...,171718.0,1068.0,110504.0,36686.0,23460.0,2581743.0,121048.0,147051.0,393543.0,1920101.0
1,04001US25,49211.0,31596.0,16784.0,48209.0,40252.0,11703.0,122751.0,572.0,79101.0,...,165949.0,983.0,107344.0,35718.0,21904.0,2369856.0,109948.0,137148.0,373907.0,1748853.0
2,04043US25,3573.0,1147.0,1242.0,3620.0,1161.0,1069.0,7971.0,13.0,5112.0,...,5769.0,85.0,3160.0,968.0,1556.0,211887.0,11100.0,9903.0,19636.0,171248.0
3,040A0US25,52702.0,32694.0,18023.0,51814.0,41373.0,12730.0,130613.0,585.0,84125.0,...,171529.0,1068.0,110380.0,36656.0,23425.0,2578051.0,120891.0,146809.0,392982.0,1917369.0
4,040C0US25,52027.0,32544.0,17697.0,51408.0,41249.0,12407.0,129063.0,579.0,83185.0,...,170726.0,1068.0,109963.0,36474.0,23221.0,2541980.0,119380.0,144870.0,388637.0,1889093.0

In [30]:
FilteredFileOrg.head()
# 168

,STATE,LOGRECNO,GEOID,NATIVITY IN THE UNITED STATES for Total Population In The United States Total,NATIVITY IN THE UNITED STATES for Total Population In The United States Native,NATIVITY IN THE UNITED STATES for Total Population In The United States Foreign-Born,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households Under 3 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 3 and 4 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 5 years,...,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- Total,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- With own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Male householder no wife present -- No own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- Total,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- With own children of the householder under 18 years,SEQ64_MEDIAN FAMILY INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS BY FAMILY TYPE BY PRESENCE OF OWN CHILDREN UNDER 18 YEARS for Families Other family -- Female householder no husband present -- No own children of the householder under 18 years,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Employed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years Less than high school graduate In labor force Civilian Unemployed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Employed,SEQ78_EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS for Population 25 To 64 Years High school graduate includes equivalency In labor force Civilian Unemployed
0,MA,1,04000US25,6742143.0,5680682.0,1061461.0,1384240.0,210811.0,152154.0,74087.0,...,57815,48540,65264,40004,29020,55608,155152.0,20969.0,596395.0,55150.0
1,MA,2,04001US25,6204458.0,5170026.0,1034432.0,1272221.0,198339.0,142001.0,68810.0,...,57447,47248,65163,39155,28384,54984,148924.0,19942.0,543175.0,51799.0
2,MA,3,04043US25,537685.0,510656.0,27029.0,112019.0,12472.0,10153.0,5277.0,...,61691,57172,66930,57125,47369,65298,6228.0,1027.0,53220.0,3351.0
3,MA,4,040A0US25,6731449.0,5671874.0,1059575.0,1382109.0,210514.0,151903.0,74003.0,...,57722,48481,65155,40000,29021,55614,154859.0,20969.0,594991.0,55039.0
4,MA,5,040C0US25,6643396.0,5589108.0,1054288.0,1366073.0,208063.0,150446.0,73301.0,...,57953,48476,65453,40034,28978,55682,153551.0,20699.0,586181.0,54153.0

In [31]:
FilteredFileOrg2 = pd.merge(FilteredFileOrg, FilteredFileAdd, on = ['GEOID'], how = "left")   
#FilteredFile_CHECK = FilteredFile_CHECK.drop(['Unnamed: 0'], 1)

In [32]:
FilteredFileOrg2.head()
#204

,STATE,LOGRECNO,GEOID,NATIVITY IN THE UNITED STATES for Total Population In The United States Total,NATIVITY IN THE UNITED STATES for Total Population In The United States Native,NATIVITY IN THE UNITED STATES for Total Population In The United States Foreign-Born,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households Under 3 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 3 and 4 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 5 years,...,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 15 to 17 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 18 to 24 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 25 to 34 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Enrolled in private college or graduate school 35 years and over,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 15 to 17 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 18 to 24 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 25 to 34 years,SEQ41_SEX BY COLLEGE OR GRADUATE SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 15 YEARS AND OVER for Population 15 Years And Over Female Not enrolled in college or graduate school 35 years and over
0,MA,1,04000US25,6742143.0,5680682.0,1061461.0,1384240.0,210811.0,152154.0,74087.0,...,171718.0,1068.0,110504.0,36686.0,23460.0,2581743.0,121048.0,147051.0,393543.0,1920101.0
1,MA,2,04001US25,6204458.0,5170026.0,1034432.0,1272221.0,198339.0,142001.0,68810.0,...,165949.0,983.0,107344.0,35718.0,21904.0,2369856.0,109948.0,137148.0,373907.0,1748853.0
2,MA,3,04043US25,537685.0,510656.0,27029.0,112019.0,12472.0,10153.0,5277.0,...,5769.0,85.0,3160.0,968.0,1556.0,211887.0,11100.0,9903.0,19636.0,171248.0
3,MA,4,040A0US25,6731449.0,5671874.0,1059575.0,1382109.0,210514.0,151903.0,74003.0,...,171529.0,1068.0,110380.0,36656.0,23425.0,2578051.0,120891.0,146809.0,392982.0,1917369.0
4,MA,5,040C0US25,6643396.0,5589108.0,1054288.0,1366073.0,208063.0,150446.0,73301.0,...,170726.0,1068.0,109963.0,36474.0,23221.0,2541980.0,119380.0,144870.0,388637.0,1889093.0

In [33]:
#Median Household Income Enrollment

FilteredFilep2 = FilteredFile
#FilteredFileOrg = pd.read_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FilteredFile.csv", sep=',', encoding='utf-8')

#fullfile = pd.read_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FullFile.csv", engine='python')

cols =[x for x in fullfile.columns[fullfile.columns.str.contains('STATE|LOGRECNO|GEOID|ATTAINMENT|ENROLLMENT|INCOME|ALLOCATION OF LANGUAGE SPOKEN AT HOME FOR THE POPULATION 5 YEARS|POPULATION UNDER 18 YEARS BY AGE|POVERTY STATUS IN THE PAST 12 MONTHS BY SEX BY AGE for Population')]]

fullfile2 = fullfile[cols]

fullfile2.columns = fullfile2.columns.str.strip().str.replace("%", '').str.replace('"', '')

cols2 =[x for x in fullfile2.columns[fullfile2.columns.str.contains('GEOID|HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households')]]

FilteredFileAdd2 = fullfile2[cols2]



#--File59

#HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households

In [34]:
FilteredFileAdd2
#20

,GEOID,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Total,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Less than $10000,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $10000 to $14999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $15000 to $19999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $20000 to $24999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $25000 to $29999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $30000 to $34999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $35000 to $39999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $40000 to $44999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $45000 to $49999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $50000 to $59999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $60000 to $74999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $75000 to $99999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $100000 to $124999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $125000 to $149999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $150000 to $199999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $200000 or more,SEQ59_MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Median household income in the past 12 months in 2016 inflation-adjusted dollars,SEQ59_AGGREGATE HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Aggregate household income in the past 12 months in 2016 inflation-adjusted dollars
0,04000US25,2558889.0,153029.0,126832.0,107494.0,103045.0,91543.0,98585.0,89942.0,89629.0,81469.0,167450.0,229018.0,318777.0,256264.0,182821.0,216817.0,246174.0,70954,248968319300
1,04001US25,2357935.0,147392.0,121503.0,101975.0,96997.0,85562.0,92082.0,83819.0,82998.0,75423.0,154542.0,210387.0,289704.0,232539.0,164330.0,196242.0,222440.0,69430,226186299500
2,04043US25,200954.0,5637.0,5329.0,5519.0,6048.0,5981.0,6503.0,6123.0,6631.0,6046.0,12908.0,18631.0,29073.0,23725.0,18491.0,20575.0,23734.0,87619,22782019800
3,040A0US25,2555053.0,152937.0,126705.0,107427.0,102951.0,91462.0,98416.0,89909.0,89511.0,81338.0,167099.0,228586.0,318401.0,255681.0,182470.0,216417.0,245743.0,70926,248509812700
4,040C0US25,2518530.0,151210.0,124568.0,105272.0,101142.0,89961.0,96300.0,88242.0,88024.0,79885.0,164207.0,224845.0,313318.0,252311.0,180468.0,214691.0,244086.0,71166,245693938900
5,040C1US25,548297.0,55015.0,37702.0,26953.0,24584.0,20926.0,21488.0,19571.0,20170.0,17228.0,35371.0,46707.0,58281.0,46835.0,31788.0,37601.0,48077.0,58379,48899134000
6,040C2US25,1970233.0,96195.0,86866.0,78319.0,76558.0,69035.0,74812.0,68671.0,67854.0,62657.0,128836.0,178138.0,255037.0,205476.0,148680.0,177090.0,196009.0,74752,196794804900
7,040E0US25,36523.0,1727.0,2137.0,2155.0,1809.0,1501.0,2116.0,1667.0,1487.0,1453.0,2892.0,3741.0,5083.0,3370.0,2002.0,1726.0,1657.0,57441,2815873800
8,040E1US25,8336.0,385.0,684.0,649.0,473.0,449.0,503.0,429.0,376.0,292.0,624.0,1018.0,1062.0,624.0,253.0,265.0,250.0,48784,538645700
9,040E2US25,28187.0,1342.0,1453.0,1506.0,1336.0,1052.0,1613.0,1238.0,1111.0,1161.0,2268.0,2723.0,4021.0,2746.0,1749.0,1461.0,1407.0,60059,2277228100
10,040G0US25,3836.0,92.0,127.0,67.0,94.0,81.0,169.0,33.0,118.0,131.0,351.0,432.0,376.0,583.0,351.0,400.0,431.0,89428,458506600
11,040H0US25,40359.0,1819.0,2264.0,2222.0,1903.0,1582.0,2285.0,1700.0,1605.0,1584.0,3243.0,4173.0,5459.0,3953.0,2353.0,2126.0,2088.0,59902,3274380400
12,05000US25001,94351.0,3923.0,4324.0,3961.0,4756.0,3622.0,4341.0,3641.0,4430.0,3484.0,6628.0,10523.0,13183.0,9230.0,6468.0,6033.0,5804.0,65382,8230757700
13,05000US25003,54854.0,3374.0,3511.0,3239.0,2964.0,2902.0,2705.0,2520.0,2563.0,2473.0,4335.0,5502.0,6811.0,4077.0,2916.0,2474.0,2488.0,52253,3934756200
14,05000US25005,212933.0,13363.0,14389.0,11216.0,9927.0,8915.0,9089.0,9207.0,8168.0,7823.0,15161.0,19858.0,27667.0,20167.0,13709.0,13904.0,10370.0,59343,16410004600
15,05000US25007,6134.0,342.0,212.0,259.0,148.0,260.0,495.0,250.0,265.0,203.0,433.0,497.0,801.0,720.0,383.0,321.0,545.0,63534,616290600
16,05000US25009,288291.0,16376.0,15055.0,12115.0,11291.0,10920.0,10964.0,10334.0,9778.0,8905.0,18797.0,26783.0,36356.0,27624.0,20248.0,25105.0,27640.0,70886,27850950500
17,05000US25011,30389.0,1385.0,1925.0,1896.0,1661.0,1241.0,1621.0,1417.0,1222.0,1250.0,2459.0,3244.0,4282.0,2650.0,1619.0,1405.0,1112.0,56347,2199583200
18,05000US25013,177153.0,14008.0,12860.0,10614.0,9744.0,8331.0,8900.0,8294.0,7390.0,6877.0,12885.0,16042.0,21568.0,14969.0,9425.0,8830.0,6416.0,51005,12203274200
19,05000US25015,58448.0,3940.0,3173.0,2371.0,2350.0,2830.0,2719.0,2358.0,2275.0,1946.0,4277.0,5317.0,8106.0,5888.0,3920.0,3641.0,3337.0,62608,4825912000
20,05000US25017,587735.0,26864.0,20778.0,19322.0,19014.0,16632.0,17975.0,16391.0,17340.0,16149.0,35231.0,46952.0,71775.0,62990.0,49249.0,65513.0,85560.0,89019,69659518800
21,05000US25019,3836.0,92.0,127.0,67.0,94.0,81.0,169.0,33.0,118.0,131.0,351.0,432.0,376.0,583.0,351.0,400.0,431.0,89428,458506600
22,05000US25021,260061.0,11161.0,8888.0,7876.0,8327.0,7484.0,7714.0,7276.0,7601.0,7062.0,14120.0,22351.0,32250.0,28580.0,21434.0,28318.0,39619.0,90226,32128798700
23,05000US25023,182252.0,8041.0,5980.0,6376.0,6652.0,5990.0,7220.0,6391.0,6478.0,5830.0,11781.0,17046.0,25077.0,20673.0,14530.0,17232.0,16955.0,77627,18199961400
24,05000US25025,299658.0,33576.0,20479.0,14384.0,12981.0,11107.0,11036.0,10324.0,11101.0,9354.0,19834.0,25792.0,31223.0,26491.0,17027.0,20497.0,24452.0,57439,25934669500
25,05000US25027,302794.0,16584.0,15131.0,13798.0,13136.0,11228.0,13637.0,11506.0,10900.0,9982.0,21158.0,28679.0,39302.0,31622.0,21542.0,23144.0,21445.0,67005,26315335500
26,06000US2500100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,.,.
27,06000US2500103690,18953.0,1044.0,908.0,858.0,929.0,652.0,759.0,663.0,787.0,682.0,1603.0,2411.0,2352.0,1729.0,1199.0,1117.0,1260.0,63549,1644906200
28,06000US2500107175,8354.0,331.0,279.0,319.0,524.0,327.0,399.0,326.0,341.0,151.0,539.0,911.0,1335.0,934.0,685.0,550.0,403.0,70304,713375300
29,06000US2500107980,4280.0,143.0,203.0,128.0,239.0,122.0,126.0,159.0,252.0,186.0,233.0,530.0,530.0,419.0,301.0,273.0,436.0,67340,411210400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53709,86000US99786,82.0,7.0,1.0,5.0,7.0,2.0,9.0,6.0,10.0,1.0,3.0,7.0,10.0,4.0,2.0,8.0,0.0,41429,4784100
53710,86000US99788,38.0,2.0,1.0,5.0,3.0,6.0,7.0,0.0,2.0,2.0,2.0,6.0,0.0,2.0,0.0,0.0,0.0,32500,1495400
53711,86000US99789,93.0,0.0,0.0,0.0,2.0,4.0,3.0,2.0,2.0,4.0,4.0,17.0,21.0,13.0,10.0,5.0,6.0,84464,9067000
53712,86000US99790,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,.,NaN
53713,86000US99791,50.0,1.0,1.0,2.0,1.0,3.0,6.0,1.0,4.0,1.0,6.0,1.0,2.0,12.0,2.0,5.0,2.0,57500,4010100
53714,86000US99801,11174.0,292.0,245.0,149.0,247.0,200.0,269.0,427.0,368.0,241.0,785.0,1226.0,1949.0,1557.0,1299.0,1038.0,882.0,88442,1176893900
53715,86000US99820,122.0,11.0,3.0,11.0,29.0,5.0,12.0,4.0,6.0,2.0,13.0,4.0,9.0,4.0,0.0,6.0,3.0,30556,5823300
53716,86000US99824,964.0,67.0,14.0,15.0,58.0,22.0,46.0,12.0,24.0,43.0,62.0,135.0,138.0,106.0,91.0,61.0,70.0,71591,85521100
53717,86000US99825,33.0,0.0,0.0,0.0,0.0,6.0,0.0,3.0,0.0,0.0,0.0,6.0,5.0,7.0,6.0,0.0,0.0,85750,2679300
53718,86000US99826,237.0,13.0,0.0,13.0,7.0,4.0,15.0,5.0,17.0,8.0,53.0,11.0,47.0,7.0,5.0,32.0,0.0,57019,17169500
53719,86000US99827,1199.0,56.0,54.0,47.0,17.0,69.0,155.0,63.0,76.0,23.0,86.0,130.0,140.0,121.0,49.0,35.0,78.0,52469,87679600
53720,86000US99829,284.0,9.0,11.0,16.0,14.0,18.0,21.0,7.0,17.0,12.0,18.0,34.0,46.0,16.0,19.0,20.0,6.0,59167,19963300
53721,86000US99830,197.0,7.0,12.0,9.0,29.0,9.0,11.0,10.0,13.0,6.0,24.0,22.0,18.0,17.0,3.0,6.0,1.0,44250,10689300
53722,86000US99832,44.0,0.0,0.0,2.0,5.0,0.0,0.0,1.0,4.0,6.0,5.0,6.0,4.0,3.0,4.0,4.0,0.0,54500,3203900
53723,86000US99833,1237.0,62.0,75.0,65.0,60.0,56.0,42.0,25.0,35.0,36.0,108.0,156.0,147.0,132.0,61.0,121.0,56.0,63940,102427100
53724,86000US99835,3504.0,188.0,108.0,133.0,84.0,139.0,87.0,191.0,83.0,147.0,253.0,457.0,566.0,410.0,253.0,234.0,171.0,70160,289899700
53725,86000US99836,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,3.0,0.0,2.0,0.0,0.0,64500,952600
53726,86000US99840,428.0,2.0,8.0,15.0,19.0,11.0,8.0,12.0,21.0,31.0,60.0,66.0,55.0,53.0,36.0,22.0,9.0,64853,33548100
53727,86000US99841,87.0,0.0,2.0,5.0,10.0,0.0,17.0,0.0,3.0,0.0,13.0,5.0,12.0,14.0,0.0,6.0,0.0,54375,5767300
53728,86000US99901,5209.0,167.0,246.0,198.0,222.0,221.0,321.0,172.0,222.0,231.0,481.0,480.0,761.0,540.0,329.0,311.0,307.0,64162,421664200
53729,86000US99903,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,.,NaN
53730,86000US99918,98.0,12.0,0.0,7.0,5.0,9.0,5.0,5.0,0.0,0.0,3.0,21.0,27.0,0.0,4.0,0.0,0.0,60577,5380500
53731,86000US99919,338.0,21.0,4.0,15.0,37.0,13.0,13.0,10.0,15.0,2.0,31.0,43.0,50.0,40.0,31.0,11.0,2.0,62794,22867700
53732,86000US99921,682.0,34.0,31.0,45.0,23.0,36.0,37.0,24.0,37.0,25.0,50.0,59.0,89.0,85.0,53.0,34.0,20.0,59844,49322500
53733,86000US99922,96.0,2.0,8.0,12.0,15.0,8.0,7.0,10.0,2.0,5.0,6.0,6.0,8.0,4.0,3.0,0.0,0.0,31500,4071100
53734,86000US99923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,.,.
53735,86000US99925,337.0,26.0,18.0,39.0,19.0,23.0,21.0,17.0,10.0,21.0,27.0,24.0,25.0,38.0,22.0,1.0,6.0,41964,19077000
53736,86000US99926,449.0,24.0,7.0,22.0,32.0,21.0,30.0,20.0,19.0,28.0,37.0,50.0,47.0,51.0,7.0,44.0,10.0,54519,31777900
53737,86000US99927,58.0,22.0,0.0,17.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18529,1179700
53738,86000US99929,1037.0,38.0,52.0,45.0,112.0,47.0,35.0,48.0,69.0,47.0,110.0,97.0,115.0,106.0,43.0,48.0,25.0,52452,68025500

In [35]:
FilteredFile_CHECK = pd.merge(FilteredFileOrg2, FilteredFileAdd2, on = ['GEOID'], how = "left")   
#FilteredFile_CHECK = FilteredFile_CHECK.drop(['Unnamed: 0'], 1)

In [36]:
FilteredFile_CHECK.head()
#223

,STATE,LOGRECNO,GEOID,NATIVITY IN THE UNITED STATES for Total Population In The United States Total,NATIVITY IN THE UNITED STATES for Total Population In The United States Native,NATIVITY IN THE UNITED STATES for Total Population In The United States Foreign-Born,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households Under 3 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 3 and 4 years,SEQ34_POPULATION UNDER 18 YEARS BY AGE for Population Under 18 Years In households 5 years,...,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $45000 to $49999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $50000 to $59999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $60000 to $74999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $75000 to $99999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $100000 to $124999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $125000 to $149999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $150000 to $199999,SEQ59_HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households $200000 or more,SEQ59_MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Median household income in the past 12 months in 2016 inflation-adjusted dollars,SEQ59_AGGREGATE HOUSEHOLD INCOME IN THE PAST 12 MONTHS IN 2016 INFLATION-ADJUSTED DOLLARS for Households Aggregate household income in the past 12 months in 2016 inflation-adjusted dollars
0,MA,1,04000US25,6742143.0,5680682.0,1061461.0,1384240.0,210811.0,152154.0,74087.0,...,81469.0,167450.0,229018.0,318777.0,256264.0,182821.0,216817.0,246174.0,70954,248968319300
1,MA,2,04001US25,6204458.0,5170026.0,1034432.0,1272221.0,198339.0,142001.0,68810.0,...,75423.0,154542.0,210387.0,289704.0,232539.0,164330.0,196242.0,222440.0,69430,226186299500
2,MA,3,04043US25,537685.0,510656.0,27029.0,112019.0,12472.0,10153.0,5277.0,...,6046.0,12908.0,18631.0,29073.0,23725.0,18491.0,20575.0,23734.0,87619,22782019800
3,MA,4,040A0US25,6731449.0,5671874.0,1059575.0,1382109.0,210514.0,151903.0,74003.0,...,81338.0,167099.0,228586.0,318401.0,255681.0,182470.0,216417.0,245743.0,70926,248509812700
4,MA,5,040C0US25,6643396.0,5589108.0,1054288.0,1366073.0,208063.0,150446.0,73301.0,...,79885.0,164207.0,224845.0,313318.0,252311.0,180468.0,214691.0,244086.0,71166,245693938900

In [37]:
FilteredFile_CHECK.to_csv("\\\\Aopscifs004.amsa.com\\fs$\\DATA\\GROUP\\Insights and Outcomes\\IOG Projects\\CPS Brockton EOC Support\\Data\\FilteredFile.csv", sep=',', encoding='utf-8')